instrumentation:
  root: src/
check:
  global:
    statements: 0
    branches: 0
    functions: 0
    lines: 0
#  each:
#    statements: 72
#    functions: 50
#    branches: 72
#    lines: 72

reporting:
  print: both
  dir: reports/
  reports:
    - cobertura
    - html
    - lcovonly
    - html
    - json
  report-config:
    cobertura: {file: cobertura/coverage.xml}
    json: {file: json/coverage.json}
    lcovonly: {file: lcov/lcov.info}
    text: {file: null}
